[package]
name = "rust-poc-s3-minio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
futures = "0.3.21"
rust-s3 = "0.30.0"
tokio = {version="1.17.0", features=["full"]}
